# Generated by Django 5.2.4 on 2025-08-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardImg', models.ImageField(upload_to='static/images')),
                ('guardName', models.CharField(max_length=255)),
                ('guardDesignation', models.CharField(max_length=255)),
            ],
        ),
    ]
