# Generated by Django 5.2.4 on 2025-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesImg', models.ImageField(upload_to='static/images')),
                ('servicesName', models.CharField(max_length=255)),
                ('servicesDescription', models.CharField(max_length=255)),
            ],
        ),
    ]
