# Generated by Django 5.2.4 on 2025-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_registration_alter_services_servicesdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
