# Generated by Django 4.2.9 on 2026-03-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_registration_email_alter_registration_fname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=25)),
                ("modelselection", models.CharField(max_length=20)),
                ("amount", models.CharField(max_length=5)),
                ("message", models.TextField()),
                ("order_id", models.CharField(blank=True, max_length=100)),
                ("paid", models.BooleanField(default=False)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField(max_length=7)),
                ("ename", models.CharField(max_length=50)),
                ("eemail", models.EmailField(max_length=255)),
                ("econtact", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=100)),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.services"
                    ),
                ),
            ],
        ),
    ]
